# Generated by Django 3.2.15 on 2022-09-17 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracteristicaparqueadero',
            options={'verbose_name': 'Caracteristica Parqueadero', 'verbose_name_plural': 'Caracteristica Parqueaderos'},
        ),
        migrations.AlterModelOptions(
            name='numerobano',
            options={'verbose_name': 'Número Baños', 'verbose_name_plural': 'Número Baños'},
        ),
        migrations.AlterModelOptions(
            name='numerohabitacion',
            options={'verbose_name': 'Número Habitación', 'verbose_name_plural': 'Número Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='numeroparqueadero',
            options={'verbose_name': 'Número Parqueadero', 'verbose_name_plural': 'Número Parqueaderos'},
        ),
        migrations.AlterModelOptions(
            name='propiedad',
            options={'verbose_name': 'Propiedad', 'verbose_name_plural': 'Propiedades'},
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='Estrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='configuraciones.estrato'),
        ),
        migrations.DeleteModel(
            name='Estrato',
        ),
    ]
