# Generated by Django 3.2.15 on 2022-09-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_auto_20220916_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaracteristicaParqueadero',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='EstadoPropiedad',
        ),
        migrations.DeleteModel(
            name='NumeroBano',
        ),
        migrations.DeleteModel(
            name='NumeroHabitacion',
        ),
        migrations.DeleteModel(
            name='NumeroParqueadero',
        ),
        migrations.DeleteModel(
            name='TiempoConstruido',
        ),
        migrations.DeleteModel(
            name='TipoOferta',
        ),
        migrations.DeleteModel(
            name='TipoParqueadero',
        ),
        migrations.DeleteModel(
            name='TipoPropiedad',
        ),
    ]
