# Generated by Django 3.2.15 on 2022-09-23 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_auto_20220922_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='Estrato',
            new_name='estrato',
        ),
    ]
