# Generated by Django 3.2.15 on 2022-09-29 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_rename_estrato_propiedad_estrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='estrato',
        ),
    ]
