# Generated by Django 3.2.15 on 2022-09-29 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0006_remove_propiedad_estrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='Localizacion',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='agente',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='anio_construccion',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='area_construida',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='area_fondo',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='area_privada',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='caracteristica_parqueadero',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='estado_propiedad',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='incluye_administracion',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='numero_bano',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='numero_habitacion',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='numero_parqueadero',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='numero_piso',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='tiempo_construido',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='tipo_oferta',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='tipo_parqueadero',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='tipo_propiedad',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='valor_administracion',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='valor_arriendo',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='valor_metro',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='video',
        ),
    ]
