# Generated by Django 3.2.15 on 2022-09-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0013_auto_20220928_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='matricula_inmobiliaria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
